# Generated by Django 4.0.5 on 2022-07-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, verbose_name='Название слайда')),
                ('image_1', models.ImageField(default='', upload_to='slider_images/%Y-year/%m-month/%d-day/', verbose_name='Фото слайда 1')),
                ('image_2', models.ImageField(default='', upload_to='slider_images/%Y-year/%m-month/%d-day/', verbose_name='Фото слайда 2')),
            ],
        ),
        migrations.CreateModel(
            name='SystemCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL адрес категории')),
            ],
            options={
                'verbose_name': 'Системные категории',
                'verbose_name_plural': 'Системные категории',
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image_1',
            field=models.ImageField(blank=True, default='', upload_to='product_images/%Y-year/%m-month/%d-day/', verbose_name='Фото товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, default='', upload_to='product_images/%Y-year/%m-month/%d-day/', verbose_name='Фото товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, default='', upload_to='product_images/%Y-year/%m-month/%d-day/', verbose_name='Фото товара'),
        ),
    ]
