# Generated by Django 4.0.5 on 2022-07-12 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homeslider_systemcategories_remove_product_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Название месседжера')),
            ],
        ),
        migrations.AddField(
            model_name='systemcategories',
            name='pod_cat',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.contactsubcat'),
        ),
    ]
