# Generated by Django 4.0.5 on 2022-07-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_systemcategories_pod_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemcategories',
            name='pod_cat',
        ),
        migrations.AddField(
            model_name='systemcategories',
            name='pod_cat',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='pod_cat', to='home.contactsubcat'),
        ),
    ]
