# Generated by Django 4.0.5 on 2022-07-12 16:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_systemcategories_pod_cat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
