# Generated by Django 4.0.5 on 2022-07-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_title',
            field=models.ImageField(blank=True, default='', upload_to='product_images/title/', verbose_name='Фото товара 600 x 600'),
        ),
    ]
