# Generated by Django 4.0.5 on 2022-07-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_product_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_1',
            field=models.ImageField(blank=True, default='', upload_to='product_images/%Y-year/%m-month/%d-day/', verbose_name='Фото товара 2294 x 1947'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, default='', upload_to='product_images/%Y-year/%m-month/%d-day/', verbose_name='Фото товара 2294 x 1947'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, default='', upload_to='product_images/%Y-year/%m-month/%d-day/', verbose_name='Фото товара 2294 x 1947'),
        ),
    ]
