# Generated by Django 4.0.5 on 2022-07-29 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_category_name_alter_product_image_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemcategories',
            name='pod_cat',
        ),
        migrations.DeleteModel(
            name='ContactSubCat',
        ),
    ]
