# Generated by Django 4.0.5 on 2022-08-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_systemcategories_pod_cat_delete_contactsubcat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(default='', related_name='cat', to='home.category', verbose_name='Категории'),
        ),
    ]
