# Generated by Django 4.0.5 on 2022-08-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_product_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(default='', related_name='products', to='home.category', verbose_name='Категории'),
        ),
    ]
