# Generated by Django 3.2.5 on 2022-08-11 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20220811_1851'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactModel',
        ),
    ]
