# Generated by Django 3.2.5 on 2022-08-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_contactmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Ваш номер телефона'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='message',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ваше имя'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Предмет обращения'),
        ),
    ]
