# Generated by Django 3.2.5 on 2022-08-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_product_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_title',
            field=models.ImageField(blank=True, default='', upload_to='product_images/title/', verbose_name='Фото товара 600 x 600'),
        ),
    ]
